"""booking source, status and change history

Revision ID: 1b8c49710f4d
Revises: 4142672a4d16
Create Date: 2026-10-08 23:42:21.396699

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b8c49710f4d'
down_revision: str | None = '4142672a4d16'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['baseline_schedule_entries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_changes_entry_id'), 'booking_changes', ['entry_id'], unique=False)
    op.add_column('baseline_schedule_entries', sa.Column('source', sa.String(length=20), server_default='enterprise', nullable=False))
    op.add_column('baseline_schedule_entries', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    op.add_column('baseline_schedule_entries', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # batch mode so SQLite (dev) can drop columns by rebuilding the table.
    with op.batch_alter_table('baseline_schedule_entries') as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('status')
        batch_op.drop_column('source')
    op.drop_index(op.f('ix_booking_changes_entry_id'), table_name='booking_changes')
    op.drop_table('booking_changes')
