"""initial schema

Revision ID: e15a93ddfdcc
Revises: 
Create Date: 2026-09-15 13:55:28.581477

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15a93ddfdcc'
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('invalid_rows', sa.Integer(), nullable=False),
    sa.Column('is_active_baseline', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('building', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=True),
    sa.Column('weekly_available_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labs_code'), 'labs', ['code'], unique=True)
    op.create_table('baseline_schedule_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=False),
    sa.Column('class_type', sa.String(length=50), nullable=True),
    sa.Column('lab_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('delivery_weeks', sa.JSON(), nullable=False),
    sa.Column('session_frequency', sa.String(length=20), nullable=False),
    sa.Column('cohort_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('error_type', sa.String(length=50), nullable=False),
    sa.Column('raw_value', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baseline_entry_id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_entry_id'], ['baseline_schedule_entries.id'], ),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_occurrences')
    op.drop_table('ingestion_errors')
    op.drop_table('baseline_schedule_entries')
    op.drop_index(op.f('ix_labs_code'), table_name='labs')
    op.drop_table('labs')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
